dev_user: "{{ lookup('env', 'USER') }}"
dev_packages:
  - vim
  - git
  - zsh
  - tmux
  - jq
  - nmap
  - curl
  - make
  - htop
  - ripgrep
  - unzip
  - gpg

dev_shell: "{{ '/bin/zsh' if ansible_os_family == 'Darwin' else '/usr/bin/zsh' }}"
dev_shell_config_folder: ~/.config/{{ dev_user }}
dev_shell_config_file: "{{ dev_shell_config_folder }}/conf.sh"
dev_oh_my_zsh_theme: powerlevel10k/powerlevel10k
dev_powerlevel10k_url: https://github.com/romkatv/powerlevel10k.git
dev_powerlevel_10k_fonts:
  - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
  - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
  - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
  - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf

dev_private_github_key: ~/.ssh/github # Kan behövas att ändras

dev_git_config:
  - key: user.name
    value: "{{ dev_git_config_user | default(dev_user) }}"
  - key: user.email
    value: "{{ dev_git_config_email | default(dev_user + '@example.com') }}"
  - key: core.editor
    value: vim

# dev_git_config_user: ~
# dev_git_config_email: ~
